apiVersion: apps/v1
kind: Deployment
metadata:
  name: boot-app
  labels:
    app: boot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boot-app
  template:
    metadata:
      labels:
        app: boot-app
    spec:
      containers:
      - name: spring-boot-app
        image: soumyahe/final-cicd:11
        ports:
        - containerPort: 8080
